// Code generated by kanban/gen. DO NOT EDIT.

package kanban

// Version ...
var Version = "v1.7.0-beta1"

// Copyright ...
var Copyright = "© 2020 - 2023 FloatTech"

// Banner ...
var Banner = "* OneBot + ZeroBot + Golang\n" +
	"* Version " + Version + " - 2023-03-01 11:21:16 +0800 CST\n" +
	"* Copyright " + Copyright + ". All Rights Reserved.\n" +
	"* Project: https://github.com/FloatTech/ZeroBot-Plugin"
