// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "v1.7.1-beta1"

// Copyright ...
var Copyright = "© 2020 - 2023 FloatTech"

// Banner ...
var Banner = "* OneBot + ZeroBot + Golang\n" +
	"* Version " + Version + " - 2023-03-25 20:09:29 +0800 CST\n" +
	"* Copyright " + Copyright + ". All Rights Reserved.\n" +
	"* Project: https://github.com/FloatTech/ZeroBot-Plugin"
