name: PullLint
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
jobs:
  # This workflow closes invalid PR
  close-pr:
    name: closepr
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Close PR if commit message contains ".go"
        if: contains(github.event.pull_request.title, '.go')
        uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "非法PR. 请`fork`后修改自己的仓库, 而不是向主仓库提交更改. 如果您确信您的PR是为了给主仓库新增功能或修复bug, 请更改默认PR标题. **注意**: 如果您再次触发本提示, 则有可能导致账号被封禁."

  golangci:
    needs: close-pr
    if: ${{ !contains(github.event.pull_request.title, '.go') }}
    uses: ./.github/workflows/lib_lint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      commit_back: false

  runmain:
    needs: golangci
    if: ${{ !contains(github.event.pull_request.title, '.go') }}
    uses: ./.github/workflows/lib_run.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
