name: PushLint
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  golangci:
    uses: ./.github/workflows/lib_lint.yml
    with:
      ref: master
      commit_back: true

  runmain:
    needs: golangci
    if: ${{ !contains(github.event.pull_request.title, '.go') }}
    uses: ./.github/workflows/lib_run.yml
    with:
      ref: master

  build:
    needs: [runmain]
    uses: ./.github/workflows/lib_build.yml
    with:
      prefix: "zbp_"
      upload_artifact: true
